# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Groupsign', '0007_auto_20170425_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='revocation_requests',
            name='User',
            field=models.CharField(default=django.utils.timezone.now, max_length=1024),
            preserve_default=False,
        ),
    ]
